### ISSUE TITLE
No access at "menu"

### ISSUE THREAD

**Issue by jmguilbert** [patience4711/RPI-APS-inverters#102]
Thank you for your work.
I managed to successfully install the RPI-ECU and can access the home page.
On the other hand, the main menu to access the configurations does not appear although I am in the same local subnet at home in 10.72.3.x
Can you help me ?
Is there a configuration file that I can easily modify?
Many thanks, patience!

**Comment by patience4711** [comment]
That is because you have an odd ip number. If you can ssh into the RPI it is simple to solve.
I quote from an old issue:
**So the final conclusion is:
Open the file apache2/sites-enabled/000-default.conf
Below all appearences of 'require ip 192.168' add 'require ip 10.0' (or whatever your network starts with).
save and restart apache (service apache2 restart)**

It means in your case you should add  'require ip 10.72' like so:
![apache](https://github.com/patience4711/RPI-APS-inverters/assets/12282915/70206b8c-8138-4a3d-aad0-2a911fe380ee)
