### ISSUE TITLE
Error 100

### ISSUE THREAD

**Issue by jmguilbert** [patience4711/RPI-APS-inverters#108]
Good morning
In the morning, my rpiecu works very well. The "pwr" and "en" come back well in the application and by Mqtt. 
But after a few hours, some inverters no longer go up.
And in the logs there are:
**15:55:10 polled inv 3 error 100 invalid energy value
invdataNull.cgi: set values to null except
for totalen and time in /ramdisk/invData3** 

Do you have any ideas for work or research?
THANKS.

**Comment by jmguilbert** [comment]
Hey good morning
In the log, i found this :
10:45:17 polled inv 1 1st poll after inverter start
10:45:17 polled inv 1 ts: 8244 signal q: 43.1%
10:45:19 polled inv 2 1st poll after inverter start
10:45:20 polled inv 2 ts: 9478 signal q: 41.2%

Can you indicate me what is it the values "8244" or "9478" in red color ?
Waths hapening ?

Thanks

**Comment by patience4711** [comment]
The redcolor means that the timespan is not 5 minutes like it should. If an inverter wokes and is polled, and then goes down, and later goes up again, the timespan between the polls is 8244 seconds. In your case it seems that the inverters woke up very late or go down too soon. Probably due to a lack of daylight.

**Comment by jmguilbert** [comment]
Thank you Patience4711.
