### ISSUE TITLE
MQTT total Energy generated

### ISSUE THREAD

**Issue by AndyK8021** [patience4711/RPI-APS-inverters#115]
Hi,
is it possible to send "total Energy generated" via MQTT? At the Moment I have power, energy actual and from day. It would be nice if I can send also total energy.

**Comment by patience4711** [comment]
And what is total energy generated? The progressive total per inverter? Or total of all inverters? 
The mqtt transmissions work with the daily values because they are available in the memory. Any other accumulated values are the result of database queries which take much more cpu and time. So it might be possible but not recommended.

**Comment by AndyK8021** [comment]
Hi, thanks for your reply. Overall total energy I mean. (I think name has changed after update.

![Screenshot_20240525_100157_Samsung Internet](https://github.com/patience4711/RPI-APS-inverters/assets/152646373/e7f5d67d-3d74-408b-94a7-6fc11b648955)

**Comment by patience4711** [comment]
I am not in favor of sending automatically accumulated queries with every poll, this costs too much cpu and time. 
So i have no plans to implement this. Sorry.
