### ISSUE TITLE
Does it work with the DS3?

### ISSUE THREAD

**Issue by daice2k** [patience4711/RPI-APS-inverters#19]
I was wondering if it works with the DS3, which is the successor of the YC600?

**Comment by patience4711** [comment]
Yes we all wonder about that. Someone succeeded in pairing them but got no polling answers. More testing is needed.

**Comment by jenswalit** [comment]
Hello, thank you for the great work.
I have an AP DS3-S and would like to read it out.
Has anyone done this yet? I've tried to do the whole thing with the setting for DS1 but it doesn't work. Can I somehow rebuild the whole thing so that it also works with the DS3-S?

I ordered an ECU B. Maybe someone can help me how to sniff Zigbee. When it be here, I'll report back.



Many thanks for your help
Greetings, Jens

**Comment by daice2k** [comment]
> Yes we all wonder about that. Someone succeeded in pairing them but got no polling answers. More testing is needed.

I ordered a DS3 and will get it today. I´ll try out if it works.

**Comment by jenswalit** [comment]
> Ich habe einen DS3 bestellt und bekomme ihn heute. Ich werde es ausprobieren ob es funktioniert.
Super thank you

**Comment by patience4711** [comment]
@daice2k  @jenswalit 
To improve our software we heighly depent on guys like you who want to help. Thanks in advance and i am curious about the results. I think that when we can pair it, we also should be able to read it. 
So what i would like to know is that: 
-when we trigger a pair action, what is the answer we get, and also 
-when we trigger a poll, do we get some answer from the inverter. 
With my software we have a lot of debug options at hand, in the console we can exactly follow the zigbee communication. 

You probably live too far away from my place (Eindhoven) otherwise i could drop by with my laptop to make the sniffs, you probably wouldn't even know haha. 

I also would like to propose that we continue this converstation to https://github.com/Koenkk/zigbee2mqtt/issues/4221 as the people who inverse engineered the yc600 are very interested in this subject.

**Comment by jenswalit** [comment]
Yes cool, Eindhoven is 200 km away.
My ECU hasn't arrived yet, so I'll let you know what's coming. Then I will try to send you the data from the DS3

**Comment by daice2k** [comment]
@patience4711 
> I also would like to propose that we continue this converstation to [Koenkk/zigbee2mqtt#4221](https://github.com/Koenkk/zigbee2mqtt/issues/4221) as the people who inverse engineered the yc600 are very interested in this subject.

OK I have the 2.0 running and try to give the DS3 a bit of DC through the power supply (it´s night here atm) and see what I get and post it at https://github.com/Koenkk/zigbee2mqtt/issues/4221
