### ISSUE TITLE
Implausible values on the day of the update to V2_0

### ISSUE THREAD

**Issue by kentbrock** [patience4711/RPI-APS-inverters#24]
I´ve done the update to V2_0 on the evening of the 18th Februar.  I´ve followed your instructions strictly! Started the backup an hour after sunset and recovered the backup long before midnight.

Everything seems to be fine. Today I´ve seen that there is an implausible value in the "DAILY ENERGY INVERTER 0". The value is far to high. This value leads to high values in the Inverter Statistics. 

Can I manipulate the data point myself so that the calculation fits again? 

![grafik](https://user-images.githubusercontent.com/58900372/154831131-f3ee9ee5-3f16-42c6-866b-45a765a2a49c.png)

**Comment by kentbrock** [comment]
I have noticed that there is a switch in displaying the amount of power over the day:

V 2_0:
![grafik](https://user-images.githubusercontent.com/58900372/154835708-81b6319a-a3f8-4db5-897d-bb7e8b662b89.png)

V 1_5:
![grafik](https://user-images.githubusercontent.com/58900372/154835728-606e85ad-a5e8-4a4e-a366-b1b030dc8be4.png)

These values are realistic. It seems to me that there is switch in the metric of add up the power from 1_5 to 2_0.

**Comment by patience4711** [comment]
Hi, The switch in the charts is due to the new approach as to what values are kept in the database. Before the total energy value was shown, now it is the energy increase. There it went wrong with the transistion. It should be done in the time after midnight instead of before. My bad, sorry.

To repair this we replace the data in database invEnergy for date 2022-02-18:
#type: = what you type in the console
(repace inv0 with your inverternr).
#ssh into the ecu
#open the influx shell
type: influx
#now you get the influx prompt
>
#first find the right energy value
type: use invData
Using database invData
type: select e from inv0 where time > '2022-02-18' and time < '2022-02-19' 
#The highest last value before it becomes 0 is the total energy that day
#Remember that value as you should insert that in 'invEnergy'

#now find the wrong value
type: use invEnergy
Using database invEnergy

type: select * from inv0 where time > '2022-02-18' and time < '2022-02-19'
#example output:
name: inv0
time                e
----                -
**1645225203868735727** 327  (remember **your** time value, you need it to delete and restore)

#delete the wrong value
type: delete from inv0 where time = 1645225203868735727
#check the result
type: select e from inv0 where time > '2022-02-18' and time < '2022-02-19'
#you should get no result now.

#insert the right value with the same timestamp
type: insert inv0 e=XXX.X 1645225203868735727
#check the result
type: select e from inv0 where time > '2022-02-18' and time < '2022-02-19'
#when ready 
type: exit

**Comment by kentbrock** [comment]
works perfectly! Thank you :-)

**Comment by patience4711** [comment]
With the recent versions it is possible to replace or remove wrong values from the energy database via the webinterface.
