### ISSUE TITLE
RPI-ECU_v02

### ISSUE THREAD

**Issue by Chen32220** [patience4711/RPI-APS-inverters#3]
Great new values, (only for inverter 0)

For inverter "DOM.IDX "  What is it?
I entered 895 without knowing
![Capture](https://user-images.githubusercontent.com/95560595/148689586-c1b5e0b8-39fa-4254-a34b-97dc387e282a.JPG)
![Capture1](https://user-images.githubusercontent.com/95560595/148689595-5ce3f5c7-5405-48e7-b77e-0c5d91679cb3.JPG)
![Capture2 2](https://user-images.githubusercontent.com/95560595/148689598-c20601c2-7c6a-48ef-8d54-9709518f0ed3.JPG)
![Capture 2JPG](https://user-images.githubusercontent.com/95560595/148689600-f9ffaf9a-800e-4105-ac0e-43393c358455.JPG)

**Comment by patience4711** [comment]
If you upgraded to the latest release, you could not have these daily energy values for inverter 0. Unless you forgot to make the relative database empty. These values belong to my inverter. You can get rid of them if you go to the menu databases. Choose inverter 0 and click wipe values for both databases.

The graphs for power etc work fine for all inverters?
If i understand well what you mean to say is that there are no daily energy values / statistics for other than inverter 0.?  At the first day this is normal but if this still is the situation please do the following: Go to the menu databases click inverter 1 and click query from invEnergy and send me the screenshot, so that i can see if this database is working or not. 

As for the DOMidx, this is just an id that is sent in mqtt messages to Domoticz, so that the device can be identified. I'l update that in the help page.

**Comment by Chen32220** [comment]
_The graphs for power etc work fine for all inverters?_
no: only for inv0

_If i understand well what you mean to say is that there are no daily energy values / statistics for other than inverter 0_.
Yes




![energy](https://user-images.githubusercontent.com/95560595/149652822-28cabeb0-1bee-4df8-9959-92ad66df5c04.png)
![energy1](https://user-images.githubusercontent.com/95560595/149652824-1807a8b1-b715-4408-97d1-7006bb6d3898.png)
![No data](https://user-images.githubusercontent.com/95560595/149652827-6d3e6831-af1b-43fd-a5ab-dc6381759e5d.png)
s

**Comment by patience4711** [comment]
I am testing with a fake inverter that i gave the number 3 and everything seems to work fine. From your pictures i conclude that the databases work fine, there are values in invEnergy which means that the other database is working also. 
Seems that the chart pages do not reed the database correct. You could do the following test:
- select inverter 1 on the front page and todays date in the charts page.
- open a new page and type  'http://**your_ecu_ip**/chartjs/chartdata_pe.php' in the addressbar and enter
- now you should get something like:<br>
![query_pe](https://user-images.githubusercontent.com/12282915/149802344-9ee91bfc-2eb1-4c64-92f7-59611fd250f6.jpg)
<br>This is the today's power and energy data for the chosen inverter. Do you get anything like this?

Later this week i will release a new version that has the possibility to install software updates. This means that we only have to write the image to the  sd-card once.  Now future software upgrades can be installed without losing all our settings and databases.

**Comment by Chen32220** [comment]
no doubt: all inverters transmit power and energy.
![Capture](https://user-images.githubusercontent.com/95560595/149911874-0215ca8b-0d3b-49ba-b616-f1946ee9faf2.JPG)
For inverter 0 everything is fine: detail, chart, power, energy, p&e, stats
Problem: for all the other, 1 2 3 4 5 6 7 8,
 there is no display "stats" and in "energy" the previous days are not displayed
![Capture1](https://user-images.githubusercontent.com/95560595/149913033-0e4e3f02-7877-4811-ac0d-efab6467c06a.JPG)

**Comment by patience4711** [comment]
Oke, i found the bug and corrected it. l released a new improved image 20 jan 2022.  Remember: you won't get stats and monthly energy at the first day.

**Comment by Chen32220** [comment]
Everything is fine with version1_1. Congratulation
I look forward to the file for housing
