### ISSUE TITLE
Issues connecting RPI-ECU with my Home Assistant

### ISSUE THREAD

**Issue by TheRealCryss** [patience4711/RPI-APS-inverters#95]
Hello,

The MQTT broker of Home Assistant doesn't see the RPI-ECU as a device. In the log file I can see that it recognizes the RPI-ECU when sending the test message. Credentials seem to be ok as there is no authentication failed message or such.
The MQTT broker does recognized other devices like my Roborock S5 that runs Valetudo (with MQTT enabled).

`2023-11-24 11:45:08: New client connected from 192.168.178.183:43900 as mosqpub|4796-rpiecu (p2, c1, k60, u'rpiecu').
2023-11-24 11:45:08: Client mosqpub|4796-rpiecu disconnected.`

![Bild 29 11 23 um 19 46](https://github.com/patience4711/RPI-APS-inverters/assets/128715006/2e37b88e-9191-4415-bb31-c65ef488fa51)

MQTT explorer recieves the hello test message, but nothing else.

Could you please explain how to set it up.

Thank you!

Chris

**Comment by patience4711** [comment]
As for the RPI you have to choose one of the available json formats and enable mosquitto. If you can receive the testmessage I really wouldn't know why not the other messages. To me this seems a problem of Home Assistant because the mosquito transmissions of the rpi-ecu do work. 
So unfortunately i can't help you here, I don't know anything about home assistant. Maybe you could look into the issues of the ESP-ECU, [here](https://github.com/patience4711/read-APSystems-YC600-QS1-DS3) i seem to remember that someone wrote an explanation of how to do this.
